#存档文件扩展名
save_extensions : {'.sav', '.save', '.esm', '.esp', '.bsa', '.ba2','.rpgsave', '.rmmzsave', '.phxsav'}
#扫描白名单设置
white_list_root_path : {'D:\MyDownload\Telegram': ['all'],'C:\\Users\\kongyu\\Documents': ['Phonexies']}
#扫描路径列表
scan_root_path_list : {'D:\MyDownload\Telegram', 'C:\\Users\\kongyu\\Documents'}
#备份后的存档文件列表
save_backup_path : 'D:\MyDownload\game-save-backup'
#压缩后的存档文件列表
zip_backup_path : 'D:\MyDownload\game-save-backup-zip'